
version: '3.5'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo

  tech-challenge:
    image: stylefelix/tech-challenge
    container_name: tech-challenge_container
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - redis
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - postgres

  sonarqube:
    image: sonarqube
    hostname: sonarqube
    container_name: sonarqube
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
  mongo:
    driver: bridge

volumes:
  mongodb_data:
  tech-challenge:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: