apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-java
  labels:
    app: tech-challenge-java
  annotations:
    author: G8 - 3SOAT/2023
    name: tech-challenge-service
    description: "This is the java springboot service for Tech Challenge"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-java
  template:
    metadata:
      labels:
        app: tech-challenge-java
    spec:
      containers:
      - name: tech-challenge-java
        image: stylefelix/tech-challenge-kubernetes:latest
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          limits:
            memory: "400Mi"
            cpu: "90m"
          requests:
            memory: "400Mi"
        readinessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 500
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 180
          failureThreshold: 30
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: svc-tech-challenge-java
spec:
  selector:
    app: tech-challenge-java
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
      nodePort: 31808
  type: LoadBalancer

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tech-challenge-java-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tech-challenge-java
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60