apiVersion: v1
kind: Pod
metadata:
  name: kafka-cli-list-topics
  labels:
    app: kafka-cli
spec:
  containers:
    - name: kafka-cli
      image: confluentinc/cp-kafka:7.0.1
      command:
        - sh
        - -c
        - "exec kafka-topics --list --bootstrap-server kafka-0.kafka.kafka.svc.cluster.local:9092"
      resources: {}
      stdin: true
      tty: true
  restartPolicy: Never
  dnsPolicy: ClusterFirst
